// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Keldrion, LLC and contributors

/**
 * Generate the built-in dictionaries from `locales/*.json`.
 *
 * The Rust server injects the dictionaries it loaded at startup, which is what
 * makes a `locales/` directory on disk re-localize the UI with no rebuild. But
 * the artifact must also work when opened directly from `file://`, where no
 * server exists — so the dictionaries have to be baked in as well.
 *
 * This mirrors `I18n::ui_dictionaries()` in Rust: take every `ui.*` key, strip
 * the prefix, and group by locale. Keep the two in step.
 *
 * Emitted as a JS module rather than fetched JSON: the artifact makes no
 * requests, not even same-origin ones.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const localesDir = resolve(repoRoot, 'locales');
// Deliberately OUTSIDE web/src: the generated file is a build output, and the
// cargo build watches web/src. Writing it inside the source tree would make
// every build invalidate its own watch set and rebuild forever.
const outFile = resolve(here, '..', '.generated', 'locales.js');

const LOCALES = ['en', 'zh-CN'];
const PREFIX = 'ui.';

function readJson(file) {
  return JSON.parse(readFileSync(resolve(localesDir, file), 'utf8'));
}

const dictionaries = {};
for (const code of LOCALES) {
  const raw = readJson(`${code}.json`);
  const ui = {};
  for (const [key, value] of Object.entries(raw)) {
    if (key.startsWith(PREFIX)) ui[key.slice(PREFIX.length)] = value;
  }
  dictionaries[code] = ui;
}

const termbase = readJson('termbase.json').terms ?? {};

const banner = `// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Keldrion, LLC and contributors
//
// GENERATED by web/scripts/gen-locales.mjs from locales/*.json — do not edit.
// Run \`npm run build\` (or \`npm run gen\`) after changing a locale file.
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `${banner}
export const FALLBACK_DICTIONARIES = ${JSON.stringify(dictionaries, null, 2)};

export const FALLBACK_TERMS = ${JSON.stringify(termbase, null, 2)};
`,
);

const counts = Object.entries(dictionaries)
  .map(([code, keys]) => `${code}: ${Object.keys(keys).length}`)
  .join(', ');
console.log(`generated ${outFile}`);
console.log(`  ${counts}`);
console.log(`  termbase terms: ${Object.keys(termbase).length}`);
